// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/sights": {
            "get": {
                "description": "Fetch all sights from the database",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sights"
                ],
                "summary": "Get all sights",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.SightsSuccessResponseType"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.SightsErrorResponseType"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "response.Sight": {
            "type": "object",
            "properties": {
                "buildingNumber": {
                    "type": "string"
                },
                "cityCountyDistrict": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "latitude": {
                    "type": "number"
                },
                "legalDong": {
                    "type": "string"
                },
                "longitude": {
                    "type": "number"
                },
                "name": {
                    "type": "string"
                },
                "province": {
                    "type": "string"
                },
                "ri": {
                    "type": "string"
                },
                "streetNumber": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "response.SightsErrorResponseType": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/response.Sight"
                    }
                },
                "error": {},
                "state": {
                    "type": "boolean"
                }
            }
        },
        "response.SightsSuccessResponseType": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/response.Sight"
                    }
                },
                "error": {},
                "state": {
                    "type": "boolean"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
