definitions:
  response.Sight:
    properties:
      buildingNumber:
        type: string
      cityCountyDistrict:
        type: string
      id:
        type: integer
      latitude:
        type: number
      legalDong:
        type: string
      longitude:
        type: number
      name:
        type: string
      province:
        type: string
      ri:
        type: string
      streetNumber:
        type: string
      type:
        type: string
    type: object
  response.SightsErrorResponseType:
    properties:
      data:
        items:
          $ref: '#/definitions/response.Sight'
        type: array
      error: {}
      state:
        type: boolean
    type: object
  response.SightsSuccessResponseType:
    properties:
      data:
        items:
          $ref: '#/definitions/response.Sight'
        type: array
      error: {}
      state:
        type: boolean
    type: object
info:
  contact: {}
paths:
  /sights:
    get:
      description: Fetch all sights from the database
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.SightsSuccessResponseType'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.SightsErrorResponseType'
      summary: Get all sights
      tags:
      - sights
swagger: "2.0"
